### ISSUE TITLE
Add ids to elements in weather app intro section

### ISSUE THREAD

**Issue by anttival** [fmidev/weather-app#644]
Ids are missing from every element in "intro" section's views (see images) from first to last when user has accepted terms of use. ![Image](https://github.com/user-attachments/assets/68dbb012-58c5-4514-b870-f904749047af)
![Image](https://github.com/user-attachments/assets/a369d0aa-ba77-4c35-bc1b-8fd3e9582522)

**Comment by geosaaga** [comment]
This is now done and available in the latest APK. It was not possible to add all testIDs because SVG icons doesn't support it in react-native. Pagination also uses custom implementation that is not mapped to any native component. Added testIDs to pagination, but not sure are those usable for testing.

testIDs are prefixed with `boarding_` and `setup_`, because there are two different React Native screens. testIDs can be found from PR files https://github.com/fmidev/weather-app/pull/645/files
